language: php

jobs:
  include:
    - php:  7.1
    - php:  7.2
    - php:  7.3
    - php:  7.4
    - php:  8.0

install:
  - composer install
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then composer require "phpunit/phpunit:7.0"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then composer require "phpunit/phpunit:8.0"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.3" ]]; then composer require "phpunit/phpunit:9.5"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.4" ]]; then composer require "phpunit/phpunit:9.5"; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "8.0" ]]; then composer require "phpunit/phpunit:9.5"; fi
